### ISSUE TITLE
Performance leak / use key

### ISSUE THREAD

**Issue by migo315** [bestit/symfony-commercetools-customer-prices-bundle#5]
Instead of query values `container="customer-prices" and value(currency="EUR") and value(customer="XYZ")` use the key instead `container="customer-prices" and key = "3027-73398-EUR"`.

The container and key is indexed. All other values are not. This can be a massive perfomance issue on big data.

**Comment by jenschude** [comment]
You could use following pattern for the container name: "customer-prices-CURRENCY-CustomerID"

So the query would use the Index again as you now could use following where:

```container = "customer-prices-EUR-3027"```

**Comment by migo315** [comment]
Thanks - I'v made the changes and published it under 0.3.0.
